### ISSUE TITLE
[tools/replay] Replay tool SIGSEV on simple vkcube with AMDGPU/Mesa

### ISSUE THREAD

**Issue by DistantThunder** [LunarG/gfxreconstruct#358]
Hi, 

Thanks for your work, it's appreciated!

I'm trying to capture a trace for a program that can crash the amdgpu driver.
I tested the GFXReconstruct Capture Layer on VKCUBE first and though the capture file was created, I cannot replay it:

## System Information
```
[...]
     Graphics:
       Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
       vendor: Sapphire Limited driver: amdgpu v: kernel bus ID: 0c:00.0 
       Display: x11 server: X.Org 1.20.8 driver: amdgpu 
       resolution: 2560x1440~144Hz 
       OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.36.0 
       5.6.11-zen1-1-zen LLVM 10.0.0) 
       v: 4.6 Mesa 20.0.6 direct render: Yes 

[...]
```

## Segfault Trace

```
(gdb) run gfxrecon_capture_20200510T160914.gfxr
Starting program: /home/_USER_/dev/gaming/gfxreconstruct/_build/tools/replay/gfxrecon-replay gfxrecon_capture_20200510T160914.gfxr
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff797c7da in ?? () from /usr/lib/libvulkan.so
#2  0x00007ffff795a8ab in ?? () from /usr/lib/libvulkan.so
#3  0x00007ffff796ffee in ?? () from /usr/lib/libvulkan.so
#4  0x00007ffff7976962 in vkCreateInstance () from /usr/lib/libvulkan.so
#5  0x0000555555b1041c in gfxrecon::decode::VulkanReplayConsumerBase::OverrideCreateInstance (this=0x7fffffffd110, original_result=VK_SUCCESS, pCreateInfo=0x555555f0c7c0, pAllocator=0x0, original_instance=..., pInstance=0x7fffffffcb48)
    at ../framework/decode/vulkan_replay_consumer_base.cpp:1439
#6  0x0000555555bf2b97 in gfxrecon::decode::VulkanReplayConsumer::Process_vkCreateInstance (this=0x7fffffffd110, returnValue=VK_SUCCESS, pCreateInfo=..., pAllocator=..., pInstance=...) at ../framework/generated/generated_vulkan_replay_consumer.cpp:44
#7  0x0000555555b6a182 in gfxrecon::decode::VulkanDecoder::Decode_vkCreateInstance (this=0x7fffffffcf00, parameter_buffer=0x555555f0e1a0 <incomplete sequence \342>, buffer_size=1025) at ../framework/generated/generated_vulkan_decoder.cpp:57
#8  0x0000555555b997f0 in gfxrecon::decode::VulkanDecoder::DecodeFunctionCall (this=0x7fffffffcf00, call_id=gfxrecon::format::ApiCall_vkCreateInstance, call_info=..., parameter_buffer=0x555555f0e1a0 <incomplete sequence \342>, buffer_size=1025)
    at ../framework/generated/generated_vulkan_decoder.cpp:8048
#9  0x0000555555afae2b in gfxrecon::decode::FileProcessor::ProcessFunctionCall (this=0x7fffffffd050, block_header=..., call_id=gfxrecon::format::ApiCall_vkCreateInstance) at ../framework/decode/file_processor.cpp:409
#10 0x0000555555afa557 in gfxrecon::decode::FileProcessor::ProcessBlocks (this=0x7fffffffd050) at ../framework/decode/file_processor.cpp:193
#11 0x0000555555afa181 in gfxrecon::decode::FileProcessor::ProcessNextFrame (this=0x7fffffffd050) at ../framework/decode/file_processor.cpp:86
#12 0x0000555555ad94e9 in gfxrecon::application::Application::PlaySingleFrame (this=0x555555f0dbe0) at ../framework/application/application.cpp:88
#13 0x0000555555ad9415 in gfxrecon::application::Application::Run (this=0x555555f0dbe0) at ../framework/application/application.cpp:62
#14 0x0000555555ac9a8f in main (argc=2, argv=0x7fffffffdf08) at ../tools/replay/desktop_main.cpp:138

```

Could someone help me figure out how to solve this so I can submit a bug report?
